# -masm=intel 
loadbuffer:
	gcc -O0 -Wall -Wpedantic -o loadbuffer.run loadbuffer.c

prefetch:
	gcc -O0 -Wall -Wpedantic -o prefetch.run prefetch.c

tlbsize:
	gcc -O0 -Wall -Wpedantic -o tlbsize.run tlbsize.c

pagesize:
	gcc -O0 -Wall -Wpedantic -o pagesize.run pagesize.c

associativity:
	gcc -O0 -Wall -Wpedantic -o associativity.run associativity.c

list_cache:
	gcc -O0 -Wall -Wpedantic -o list_cache.run list_cache.c

clean:
	rm *.run